Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,7 +11,7 @@ permissions:
 
 jobs:
   run-scripts:
-    runs-on: ubuntu-latest  # Usa un runner de Ubuntu para ejecutar los scripts.
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repository
@@ -21,18 +21,16 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y qemu-user-static
-          cd ${GITHUB_WORKSPACE}
-          pwd
-          ls
-          chmod +x /rpibsas_reaperarmhf.sh
-          chmod +x /rpibsas_reaper_Buster_Bullseye_64bit.sh 
-          chmod +x /rpibsas_reaper_bookworm.sh
+          # Asegúrate de que las rutas de los scripts sean correctas
+          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaperarmhf.sh
+          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaper_Buster_Bullseye_64bit.sh 
+          chmod +x ${GITHUB_WORKSPACE}/rpibsas_reaper_bookworm.sh
 
       - name: Run Bookworm 32-bit Script
         id: bookworm_32
         run: |
           echo "Running Bookworm 32-bit Script"
-          ./rpibsas_reaperarmhf.sh > bookworm_32_output.txt 2>&1
+          qemu-arm-static ${GITHUB_WORKSPACE}/rpibsas_reaperarmhf.sh > bookworm_32_output.txt 2>&1 || true
           echo "Versions and errors for Bookworm 32-bit" > results_armhf.txt
           echo "-----" >> results_armhf.txt
           cat bookworm_32_output.txt >> results_armhf.txt
@@ -41,8 +39,8 @@ jobs:
         id: bullseye_64
         run: |
           echo "Running Bullseye 64-bit Script"
-          ./rpibsas_reaper_Buster_Bullseye_64bit.sh > rpibsas_reaper_Buster_Bullseye_64bit_output.txt 2>&1
-          echo "Versions and errors for Buste and Bullseye 64-bit" >> results_bullseye_64.txt
+          qemu-aarch64-static ${GITHUB_WORKSPACE}/rpibsas_reaper_Buster_Bullseye_64bit.sh > rpibsas_reaper_Buster_Bullseye_64bit_output.txt 2>&1 || true
+          echo "Versions and errors for Buster and Bullseye 64-bit" >> results_bullseye_64.txt
           echo "-----" >> results_bullseye_64.txt
           cat rpibsas_reaper_Buster_Bullseye_64bit_output.txt >> results_bullseye_64.txt
 
@@ -50,7 +48,7 @@ jobs:
         id: bookworm_64
         run: |
           echo "Running Bookworm 64-bit Script"
-          ./rpibsas_reaper_bookworm.sh > rpibsas_reaper_bookworm_output.txt 2>&1
+          qemu-aarch64-static ${GITHUB_WORKSPACE}/rpibsas_reaper_bookworm.sh > rpibsas_reaper_bookworm_output.txt 2>&1 || true
           echo "Versions and errors for Bookworm 64-bit" >> results_bookworm.txt
           echo "-----" >> results_bookworm.txt
           cat rpibsas_reaper_bookworm_output.txt >> results_bookworm.txt
